# Generated by Django 5.1.4 on 2024-12-24 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('CV', models.TextField()),
                ('date_condidature', models.DateField(default=django.utils.timezone.now)),
                ('Etat_condidature', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Competances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripton', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=20)),
                ('date_obtention', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=30, unique=True)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('nom', models.CharField(blank=True, max_length=30, null=True)),
                ('prenom', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager'), ('candidate', 'Candidate')], default='candidate', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('date_de_naissance', models.DateField(default=django.utils.timezone.now)),
                ('date_aumbauche', models.DateField(default=django.utils.timezone.now)),
                ('adresse', models.CharField(max_length=30)),
                ('Historique_professionnel', models.CharField(max_length=500)),
                ('Competance_Employe', models.ManyToManyField(blank=True, related_name='comp', to='app1.competances')),
                ('Employe_Formation', models.ManyToManyField(blank=True, related_name='frm', to='app1.formations')),
                ('Service_Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.service')),
                ('Employe_Utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='app1.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('type_contrat', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=15)),
                ('salaire_monsuel', models.FloatField(max_length=20)),
                ('salaire_quotidien', models.FloatField(max_length=20)),
                ('Employe_Contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('type_conge', models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave')], max_length=15)),
                ('solde_conge', models.FloatField(max_length=10)),
                ('Employe_Conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Evaluation', models.DateField(default=django.utils.timezone.now)),
                ('criteres', models.CharField(max_length=200)),
                ('Resultat', models.CharField(max_length=200)),
                ('Commentaire', models.CharField(max_length=500)),
                ('Employe_Evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre_emploi', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('Condidat_Recrutement', models.ManyToManyField(related_name='Rcrt_cond', to='app1.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_annee', models.DateField(default=django.utils.timezone.now)),
                ('salaire_base', models.FloatField(max_length=15)),
                ('primes', models.FloatField(max_length=15)),
                ('heures_supplementaires', models.IntegerField(default=0)),
                ('retenus', models.FloatField(max_length=15)),
                ('salaire_net', models.FloatField(max_length=20)),
                ('Employe_salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='app1.employe')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='Utilisateur_Condidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condidats', to='app1.utilisateur'),
        ),
    ]
