# Generated by Django 5.1.4 on 2024-12-23 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('date_de_naissance', models.DateField(default=django.utils.timezone.now)),
                ('date_aumbauche', models.DateField(default=django.utils.timezone.now)),
                ('adresse', models.CharField(max_length=30)),
                ('Historique_professionnel', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('type_contrat', models.CharField(max_length=15)),
                ('salaire_monsuel', models.FloatField(max_length=20)),
                ('salaire_quotidien', models.FloatField(max_length=20)),
                ('Employe_Contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('type_conge', models.CharField(max_length=15)),
                ('solde_conge', models.FloatField(max_length=10)),
                ('Employe_Conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_Evaluation', models.DateField(default=django.utils.timezone.now)),
                ('criteres', models.CharField(max_length=200)),
                ('Resultat', models.CharField(max_length=200)),
                ('Commentaire', models.CharField(max_length=500)),
                ('Employe_Evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(default=django.utils.timezone.now)),
                ('annee', models.DateField(default=django.utils.timezone.now)),
                ('salaire_base', models.FloatField(max_length=15)),
                ('primes', models.FloatField(max_length=15)),
                ('heures_supplementaires', models.IntegerField(max_length=5)),
                ('retenus', models.FloatField(max_length=15)),
                ('salaire_net', models.FloatField(max_length=20)),
                ('Employe_salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='Service_Employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.service'),
        ),
    ]
