# Generated by Django 5.1.4 on 2024-12-23 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripton', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Condidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Prenom', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('CV', models.CharField(max_length=500)),
                ('date_condidature', models.DateField(default=django.utils.timezone.now)),
                ('Etat_condidature', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_formation', models.CharField(max_length=20)),
                ('date_obtention', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=30, unique=True)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='salaire',
            name='heures_supplementaires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employe',
            name='Competance_Employe',
            field=models.ManyToManyField(related_name='comp', to='app1.competances'),
        ),
        migrations.AddField(
            model_name='employe',
            name='Employe_Formation',
            field=models.ManyToManyField(related_name='frm', to='app1.formations'),
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre_emploi', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('Condidat_Recrutement', models.ManyToManyField(related_name='Rcrt_cond', to='app1.condidat')),
            ],
        ),
        migrations.AddField(
            model_name='condidat',
            name='Utilisateur_Condidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.utilisateur'),
        ),
    ]
