# Generated by Django 5.1.4 on 2024-12-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_recrutement_utilisateur_competances_formations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='LOgin',
            new_name='Login',
        ),
        migrations.AlterField(
            model_name='salaire',
            name='heures_supplementaires',
            field=models.IntegerField(default=0),
        ),
    ]
