# Generated by Django 5.1.4 on 2024-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_competances_condidat_formations_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recrutement',
            name='Etat_condidature',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Employe_Formation',
        ),
        migrations.AddField(
            model_name='employe',
            name='Employe_Formation',
            field=models.ManyToManyField(related_name='frm', to='app1.formations'),
        ),
    ]
