# Generated by Django 5.1.4 on 2025-01-02 23:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_demandeconge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAvanceSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Somme', models.FloatField()),
                ('Date_demande', models.DateField(default=django.utils.timezone.now)),
                ('num_demande', models.IntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=10)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('Employe_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_avance', to='app1.employe')),
            ],
        ),
    ]
