# Generated by Django 5.1.4 on 2024-12-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_competances_condidat_formations_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condidat',
            name='CV',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='condidat',
            name='Email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='condidat',
            name='Utilisateur_Condidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condidats', to='app1.utilisateur'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='Employe_Conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app1.employe'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('unpaid', 'Unpaid Leave'), ('maternity', 'Maternity Leave')], max_length=15),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='Employe_Contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app1.employe'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=15),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Competance_Employe',
            field=models.ManyToManyField(blank=True, related_name='comp', to='app1.competances'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='Employe_Formation',
            field=models.ManyToManyField(blank=True, related_name='frm', to='app1.formations'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='Employe_Evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app1.employe'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='Employe_salaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='app1.employe'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('candidate', 'Candidate')], max_length=30),
        ),
    ]
