# Generated by Django 5.1.4 on 2025-01-03 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_demandeavancesalaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deb', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('date_archive', models.DateField(default=django.utils.timezone.now)),
                ('type_contrat', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('internship', 'Internship')], max_length=15)),
                ('salaire_monsuel', models.FloatField(max_length=20)),
                ('salaire_quotidien', models.FloatField(max_length=20)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat', to='app1.employe')),
            ],
        ),
    ]
