# Generated by Django 5.1.4 on 2024-12-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_condidat_cv_alter_condidat_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaire',
            old_name='annee',
            new_name='mois_annee',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='mois',
        ),
    ]
