# Generated by Django 5.1.4 on 2024-12-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_recrutement_etat_condidature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recrutement',
            name='Etat_condidature',
        ),
        migrations.AddField(
            model_name='condidat',
            name='Etat_condidature',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
