# Generated by Django 5.1.4 on 2024-12-23 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_login_utilisateur_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidat',
            name='Employe_Recrutement',
        ),
        migrations.AddField(
            model_name='condidat',
            name='Condidat_Recrutement',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app1.recrutement'),
            preserve_default=False,
        ),
    ]
