# Generated by Django 5.1.4 on 2024-12-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_condidat_employe_recrutement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidat',
            name='Condidat_Recrutement',
        ),
        migrations.AddField(
            model_name='condidat',
            name='Condidat_Recrutement',
            field=models.ManyToManyField(related_name='Rcrt_cond', to='app1.recrutement'),
        ),
    ]
