# Generated by Django 5.1.4 on 2024-12-24 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_annee_salaire_mois_annee_remove_salaire_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='Employe_Utilisateur',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='app1.utilisateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formations',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recrutement',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('manager', 'Manager'), ('candidate', 'Candidate')], default='candidate', max_length=30),
        ),
    ]
