# Generated by Django 5.1.4 on 2024-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_login_utilisateur_login'),
        ('app1', '0005_remove_condidat_condidat_recrutement_and_more'),
    ]

    operations = [
    ]
